name: responsive_cs
description: "A responsive sizing package for Flutter that works across phones, tablets in both portrait and landscape modes."
version: 1.0.1
homepage: https://github.com/Cagdassrgl/responsive_cs

environment:
  sdk: ">=2.17.0 <4.0.0" # Daha geniş SDK aralığı
  flutter: ">=1.17.0" # Geniş Flutter sürüm aralığı

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Daha eski sürümle uyumlu lints

flutter:
